# Generated by Django 3.2.5 on 2021-08-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0002_client_datapack_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapack',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datapack',
            name='version',
            field=models.CharField(choices=[(4, '1.13 - 1.14.4'), (5, '1.15 - 1.16.1'), (6, '1.16.2 - 1.16.5'), (7, '1.17')], default=4, max_length=20),
        ),
    ]
