# Generated by Django 3.2.5 on 2021-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0005_item_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id_name',
            field=models.CharField(default='Default', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
