# Generated by Django 3.2.5 on 2021-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0006_auto_20210813_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(null=True, to='Minecraftable.Tag'),
        ),
    ]
