# Generated by Django 3.2.5 on 2021-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0007_alter_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='Minecraftable.Tag'),
        ),
    ]
