# Generated by Django 3.2.5 on 2021-08-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0010_rename_tag_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapack',
            name='client',
        ),
        migrations.AddField(
            model_name='datapack',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
