# Generated by Django 3.2.5 on 2021-08-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0011_auto_20210816_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='id_name',
        ),
    ]
