# Generated by Django 3.2.5 on 2021-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0012_rename_id_item_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='id_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
