# Generated by Django 3.2.5 on 2021-08-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0013_auto_20210817_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
