# Generated by Django 3.2.5 on 2021-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minecraftable', '0014_remove_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Minecraftable.Tag'),
        ),
    ]
